In [1]:
import numpy as np 
import pandas as pd

In [2]:
df1 = pd.read_csv('Q&A.csv',encoding='latin1', on_bad_lines='warn')

In [3]:
df1.head()

,Question,Answer
0,What is Python?,"A high-level, interpreted programming language."
1,Who created Python?,Guido van Rossum.
2,When was Python first released?,1991
3,Is Python free?,"Yes, it's open-source."
4,What does 'Python' mean?,Named after 'Monty Python??s Flying Circus'.

In [4]:
df2 = pd.read_csv('Python_codes.csv',encoding='latin1', on_bad_lines='warn')

In [11]:
df2.head()

,question,code
0,Create an array of length 5 which contains all...,"arr = [2, 4, 6, 8, 10]"
1,Formulate an equation to calculate the height ...,Height of triangle = opposite side length * si...
2,Write a replace method for a string class whic...,"def replace(self, replace_with):\n new_stri..."
3,Create an array of length 15 containing number...,"arr = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33..."
4,Write a function to find the number of distinc...,def find_num_distinct_states(matrix):\n sta...

In [16]:
df2 = df2.rename(columns={'question':'Question','code':'Answer'})

In [17]:
df = pd.concat([df1,df2],ignore_index=True)

In [18]:
df.head()

,Question,Answer
0,What is Python?,"A high-level, interpreted programming language."
1,Who created Python?,Guido van Rossum.
2,When was Python first released?,1991
3,Is Python free?,"Yes, it's open-source."
4,What does 'Python' mean?,Named after 'Monty Python??s Flying Circus'.

In [19]:
df.tail()

,Question,Answer
13973,"how to change [1,2,3,4] to '1234' using python",""""""""""""".join([1, 2, 3, 4])"
13974,Delete every non utf-8 symbols froms string,"line = line.decode('utf-8', 'ignore').encode('..."
13975,How to execute a command in the terminal from ...,os.system(command)
13976,Python MySQL Parameterized Queries,c.execute('SELECT * FROM foo WHERE bar = %s AN...
13977,Convert a string to datetime object in python,"dateobj = datetime.datetime.strptime(datestr, ..."

In [20]:
df.to_csv('combineDataset.csv')